development:
  domain: "localhost:3000"
  subject_prefix: "[EPIC MÖRDERSPIEL] "
  from_mail: "emgtest@tobsolution.de"
  support_mail: "support@tobsolution.de"
  default_name: "EPIC MÖRDERSPIEL"

test:
  domain: "localhost:3000"
  subject_prefix: "[EPIC MÖRDERSPIEL] "
  from_mail: "noreply@epic-mörderspiel.de"
  support_mail: "support@epic-mörderspiel.de"
  default_name: "EPIC MÖRDERSPIEL"

production:
  domain: "epic-mörderspiel.de"
  subject_prefix: "[EPIC MÖRDERSPIEL] "
  from_mail: "noreply@epic-mörderspiel.de"
  support_mail: "support@epic-mörderspiel.de"
  default_name: "EPIC MÖRDERSPIEL"