development:
  domain: "localhost:3000"
  subject_prefix: "[EPIC MÖRDERSPIEL] "
  from_mail: "emgtest@tobsolution.de"
  support_mail: "support@tobsolution.de"
  default_name: "EPIC MÖRDERSPIEL"
  facebook_app_id: 12345
  facebook_app_secret: abcd

test:
  domain: "localhost:3000"
  subject_prefix: "[EPIC MÖRDERSPIEL] "
  from_mail: "noreply@epic-mörderspiel.de"
  support_mail: "support@epic-mörderspiel.de"
  default_name: "EPIC MÖRDERSPIEL"
  facebook_app_id: 12345
  facebook_app_secret: abcd

production:
  domain: "epic-mörderspiel.de"
  subject_prefix: "[EPIC MÖRDERSPIEL] "
  from_mail: "noreply@xn--epic-mrderspiel-etb.de"
  support_mail: "support@epic-mörderspiel.de"
  default_name: "EPIC MÖRDERSPIEL"
  facebook_app_id: 12345
  facebook_app_secret: abcd
